### ISSUE TITLE
Add tooling for invoking code generation

### ISSUE THREAD

**Issue by slifty** [PhilanthropyDataCommons/sdk#5]
In #4 I started to lean in on gradle for coordinating everything about our code generation.

Some of the discussion on the PR has led me to think that gradle is probably not the right tool for coordinating dynamic methods of generating the code.  Instead, we can use gradle for management of jar dependencies and then either use bash or `npm` for actually calling the codegen commands.

Since we're using npm already for most of the pdc it seems reasonable to just leverage npm with a package.json as our point of entry.

**Comment by slifty** [comment]
Just talked with @jasonaowen about this and have some amazing updates!

1. Not going to use npm (phewf) -- a few reasons for this, but a very important one is I had forgotten: there *is* going to be code in this repository and it is going to be java code.  The templates involved the definition of a java file which specifies things like configurations and parameters.

2. We don't need our gradle file to be overly abstracted.  Parameters for languages aren't needed.  We can just have one task per language.  This is more explicit AND simpler to implement.  We can even have explicit expectations about where configuration files for each language must live / be named, and have gradle check / communicate when those expectations aren't met

3. As @bickelj noted in the original PR, we should not call java from gradle, but rather should use the codegen gradle plugin

The logic I had started to build out in that PR for supporting generation of new language templates is going to be called very few times and simply doesn't need to be a code artifact (I do think it's useful to include in the readme!)

**Comment by slifty** [comment]
The question came up about whether we should have gradle commands for things like publishing to NPM -- the answer may eventually be yes, but for the purposes of this issue I will *not* be adding that.

**Comment by reefdog** [comment]
Just noticed this has no assignee; is this a @slifty joint?
